name: Debug Log
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::Thisis a debug log"
      - run: |
          set -x
          date
          hostname
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
      - run: echo "::error::This is an error"
      - run: echo "::warning::This is an warning"
      - run: echo "::notice::This is an notice"
      - run: |
            echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
            echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
            echo "- second line" >> "${GITHUB_STEP_SUMMARY}"
